# Development overrides
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./server:/app/server
      - ./downloads:/app/downloads
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run server

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY}
      - VITE_CONTACT_EMAIL=${VITE_CONTACT_EMAIL}
      - VITE_GITHUB_URL=${VITE_GITHUB_URL}
      - VITE_TWITTER_URL=${VITE_TWITTER_URL}
    command: npm run dev
    ports:
      - "5173:5173"