# Development overrides
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./server:/app/server
      - ./downloads:/app/downloads
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:3001/api
    command: npm run server

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY}
      - VITE_CONTACT_EMAIL=${VITE_CONTACT_EMAIL}
      - VITE_GITHUB_URL=${VITE_GITHUB_URL}
      - VITE_TWITTER_URL=${VITE_TWITTER_URL}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:3001/api}
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "5173:5173"
      - "8080:80"